# Use root/example as user/password credentials
version: "3.1"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  smtp:
    image: djfarrelly/maildev
    restart: unless-stopped
    ports:
      - 127.0.0.1:${MAIL_PORT:-1025}:1025
      - 127.0.0.1:${MAIL_WEB_PORT:-1080}:1080
    environment:
      TZ: "${TIMEZONE:-America/Chicago}"
    command: |-
      bin/maildev \
      --web-user ${MAIL_USER:-user} \
      --web-pass ${MAIL_PASS:-password} \
      --incoming-user ${MAIL_USER:-user} \
      --incoming-pass ${MAIL_PASS:-password}
